apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "health-api-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "health-api-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "health-api-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "health-api-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
