version: '3.8'

services:
  ansible-test-target:
    build: .
    container_name: ansible-test-target
    ports:
      - "2222:22"
    networks:
      - ansible-test
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  ansible-test:
    driver: bridge
